# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Swagger.Client.Model.Bridge do
  @moduledoc """
  The merging of media from one or more channels.  Everyone on the bridge receives the same audio.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"technology",
    :"bridge_type",
    :"bridge_class",
    :"creator",
    :"name",
    :"channels"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"technology" => String.t,
    :"bridge_type" => String.t,
    :"bridge_class" => String.t,
    :"creator" => String.t,
    :"name" => String.t,
    :"channels" => ListString
  }
end

defimpl Poison.Decoder, for: Swagger.Client.Model.Bridge do
  import Swagger.Client.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"channels", :struct, Swagger.Client.Model.ListString, options)
  end
end

