# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Swagger.Client.Model.ChannelUserevent do
  @moduledoc """
  User-generated event with additional user-defined fields in the object.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"eventname",
    :"channel",
    :"bridge",
    :"endpoint",
    :"userevent"
  ]

  @type t :: %__MODULE__{
    :"eventname" => String.t,
    :"channel" => Channel,
    :"bridge" => Bridge,
    :"endpoint" => Endpoint,
    :"userevent" => Object
  }
end

defimpl Poison.Decoder, for: Swagger.Client.Model.ChannelUserevent do
  import Swagger.Client.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"channel", :struct, Swagger.Client.Model.Channel, options)
    |> deserialize(:"bridge", :struct, Swagger.Client.Model.Bridge, options)
    |> deserialize(:"endpoint", :struct, Swagger.Client.Model.Endpoint, options)
    |> deserialize(:"userevent", :struct, Swagger.Client.Model.Object, options)
  end
end

