# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Swagger.Client.Model.Dial do
  @moduledoc """
  Dialing state has changed.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"caller",
    :"peer",
    :"forward",
    :"forwarded",
    :"dialstring",
    :"dialstatus"
  ]

  @type t :: %__MODULE__{
    :"caller" => Channel,
    :"peer" => Channel,
    :"forward" => String.t,
    :"forwarded" => Channel,
    :"dialstring" => String.t,
    :"dialstatus" => String.t
  }
end

defimpl Poison.Decoder, for: Swagger.Client.Model.Dial do
  import Swagger.Client.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"caller", :struct, Swagger.Client.Model.Channel, options)
    |> deserialize(:"peer", :struct, Swagger.Client.Model.Channel, options)
    |> deserialize(:"forwarded", :struct, Swagger.Client.Model.Channel, options)
  end
end

