# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Swagger.Client.Model.SystemInfo do
  @moduledoc """
  Info about Asterisk
  """

  @derive [Poison.Encoder]
  defstruct [
    :"version",
    :"entity_id"
  ]

  @type t :: %__MODULE__{
    :"version" => String.t,
    :"entity_id" => String.t
  }
end

defimpl Poison.Decoder, for: Swagger.Client.Model.SystemInfo do
  def decode(value, _options) do
    value
  end
end

