# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Swagger.Client.Model.TextMessageVariable do
  @moduledoc """
  A key/value pair variable in a text message.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"key",
    :"value"
  ]

  @type t :: %__MODULE__{
    :"key" => String.t,
    :"value" => String.t
  }
end

defimpl Poison.Decoder, for: Swagger.Client.Model.TextMessageVariable do
  def decode(value, _options) do
    value
  end
end

